### ISSUE TITLE
Finish Webscraping

### ISSUE THREAD

**Issue by ishoshani** [ishoshani/LCBonAp#1]

**Comment by connorlay** [comment]
The app now scrapes the Bon's weekly menu printout and displays it as a nice Bootstrap styled table. We still need to have it group by meal, but that shouldn't be too difficult.

**Comment by ishoshani** [comment]
Dammit conner leave some glory for the rest of us. But seriously, nice work

**Comment by connorlay** [comment]
Items on the menu are now grouped by meal. Since we fixed the Sunday bug I think this issue is now closed.
![screen shot 2015-03-09 at 11 11 54 pm](https://cloud.githubusercontent.com/assets/6548350/6570085/be845e78-c6b1-11e4-922d-b25d032195b5.png)
