### ISSUE TITLE
Breaks on sunday

### ISSUE THREAD

**Issue by ishoshani** [ishoshani/LCBonAp#4]
The app displays fine for every day except sunday

**Comment by ishoshani** [comment]
by not display fine i mean that it does not show the menu at all.

**Comment by ishoshani** [comment]
![screenshot from 2015-03-15 10 37 05](https://cloud.githubusercontent.com/assets/5744154/6560568/6316db9c-c648-11e4-877d-0d8710758850.png)

**Comment by connorlay** [comment]
Fixed. Date.today.cwday indexes Sundays at 7, while the menu indexes Sundays at 0.
![screen shot 2015-03-08 at 2 46 21 pm](https://cloud.githubusercontent.com/assets/6548350/6565139/1d726c82-c66b-11e4-8aff-b8e6234f0092.png)
